baseURL = "https://kushagrasanwal.com/"
languageCode = "en-us"
title = "Kushagra Sanwal"

[params]
  description = "Economics student. VC analyst. Runner."
  author = "Kushagra Sanwal"

[menu]
  [[menu.main]]
    name = "Writing"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Reading"
    url = "/reading/"
    weight = 2
  [[menu.main]]
    name = "POW"
    url = "/pow/"
    weight = 3
  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    style = "github"
